#!/bin/bash
set -euo pipefail
ERA=${1:?Usage: drawPlots.sh ERA CHANNEL}
CHANNEL=${2:?Usage: drawPlots.sh ERA CHANNEL}
export PATH="${PWD}/python:${PATH}"

# RECO-level histkeys (SR3Mu and SR1E2Mu share muons/1-2; SR3Mu adds muons/3 and pair1/pair2;
# SR1E2Mu adds electrons/1 and dimuon)
# plot.py silently skips histkeys that are missing in the ROOT file,
# so it is safe to pass all keys to both channels.
HISTKEYs=(
    "muons/1/pt"
    "muons/1/eta"
    "muons/1/phi"
    "muons/1/mass"
    "muons/2/pt"
    "muons/2/eta"
    "muons/2/phi"
    "muons/2/mass"
    "muons/3/pt"
    "muons/3/eta"
    "muons/3/phi"
    "muons/3/mass"
    "electrons/1/pt"
    "electrons/1/eta"
    "electrons/1/phi"
    "electrons/1/mass"
    "jets/size"
    "bjets/size"
    "jets/1/pt"
    "jets/1/eta"
    "jets/2/pt"
    "jets/2/eta"
    "jets/3/pt"
    "jets/3/eta"
    "jets/4/pt"
    "jets/4/eta"
    "METv/pt"
    "pair1/mass"
    "pair1/pt"
    "pair1/deltaR"
    "pair2/mass"
    "pair2/pt"
    "pair2/deltaR"
    "dimuon/mass"
    "dimuon/pt"
    "dimuon/eta"
    "dimuon/deltaR"
    "weights/genWeight"
    "weights/pileupWeight"
    "weights/totWeight"
    "GenMatched/dimuon_mass_fromA"
    "GenMatched/muons_fromA/1/pt"
    "GenMatched/muons_fromA/1/eta"
    "GenMatched/muons_fromA/1/phi"
    "GenMatched/muons_fromA/1/mass"
    "GenMatched/muons_fromA/2/pt"
    "GenMatched/muons_fromA/2/eta"
    "GenMatched/muons_fromA/2/phi"
    "GenMatched/muons_fromA/2/mass"
    "GenMatched/electron_type"
    "GenMatched/electron_fromW/pt"
    "GenMatched/electron_fromW/eta"
    "GenMatched/electron_fromW/phi"
    "GenMatched/electron_fromW/mass"
    "GenMatched/electron_fromOffshellW/pt"
    "GenMatched/electron_fromOffshellW/eta"
    "GenMatched/electron_fromOffshellW/phi"
    "GenMatched/electron_fromOffshellW/mass"
    "GenMatched/muon1_type"
    "GenMatched/muon2_type"
    "GenMatched/muon3_type"
    "GenMatched/pair_selection_correct"
    "GenMatched/muon_fromW/pt"
    "GenMatched/muon_fromW/eta"
    "GenMatched/muon_fromW/phi"
    "GenMatched/muon_fromW/mass"
    "GenMatched/muon_fromOffshellW/pt"
    "GenMatched/muon_fromOffshellW/eta"
    "GenMatched/muon_fromOffshellW/phi"
    "GenMatched/muon_fromOffshellW/mass"
    "GenMatched/bjet_withW/pt"
    "GenMatched/bjet_withW/eta"
    "GenMatched/bjet_withHplus/pt"
    "GenMatched/bjet_withHplus/eta"
    "GenLevel/A/pt"
    "GenLevel/A/eta"
    "GenLevel/A/phi"
    "GenLevel/A/mass"
    "GenLevel/A/deltaR"
    "GenLevel/Hplus/pt"
    "GenLevel/Hplus/eta"
    "GenLevel/Hplus/phi"
    "GenLevel/Hplus/mass"
    "GenLevel/muons_fromA/1/pt"
    "GenLevel/muons_fromA/1/eta"
    "GenLevel/muons_fromA/1/phi"
    "GenLevel/muons_fromA/1/mass"
    "GenLevel/muons_fromA/2/pt"
    "GenLevel/muons_fromA/2/eta"
    "GenLevel/muons_fromA/2/phi"
    "GenLevel/muons_fromA/2/mass"
    "GenLevel/electron_fromW/pt"
    "GenLevel/electron_fromW/eta"
    "GenLevel/electron_fromOffshellW/pt"
    "GenLevel/electron_fromOffshellW/eta"
    "GenLevel/muon_fromW/pt"
    "GenLevel/muon_fromW/eta"
    "GenLevel/muon_fromOffshellW/pt"
    "GenLevel/muon_fromOffshellW/eta"
    "GenLevel/bquark_withHplus/pt"
    "GenLevel/bquark_withHplus/eta"
    "GenLevel/bquark_withW/pt"
    "GenLevel/bquark_withW/eta"
)

parallel --halt never -j 12 plot.py --era "$ERA" --channel "$CHANNEL" --histkey {} ::: "${HISTKEYs[@]}"
